urls.py
from django.urls import path

from . import views

app_name = 'balance'
urlpatterns = [
    path('dashboard/', views.AccountList.as_view(), name='account_list'),
    path('account/create/', views.AccountCreate.as_view(), name='account_create'),
    path('account/<int:pk>/', views.account_redirect, name='account_detail'),
    path('account/<int:account_pk>/<int:year>/<int:month>/', views.AccountMonth.as_view(month_format='%m'), name='account_month'),
    path('balance/update/', views.BalanceUpdate.as_view(), name='balance_update'),

    path('category/', views.CategoryList.as_view(), name='category_list'),
    path('category/<int:pk>/', views.category_redirect, name='category_detail'),
    path('category/<int:category_pk>/<int:year>/<int:month>/', views.CategoryMonth.as_view(month_format='%m'), name='category_month'),
    path('category/create/', views.CategoryCreate.as_view(), name='category_create'),

    path('transaction/<int:pk>/', views.TransactionDetail.as_view(), name='transaction_detail'),
    path('transaction/create/', views.TransactionCreate.as_view(), name='transaction_create'),
    path('transaction/<int:pk>/update/', views.TransactionUpdate.as_view(), name='transaction_update'),
    path('transaction/<int:pk>/delete/', views.TransactionDelete.as_view(), name='transaction_delete'),

    path('budget/', views.BudgetList.as_view(), name='budget_list'),
    path('budget/<int:pk>/', views.BudgetDetail.as_view(), name='budget_detail'),
    path('budget/create/', views.BudgetCreate.as_view(), name='budget_create'),

    path('budget/<int:budget_pk>/allocate/', views.AllocationCreate.as_view(), name='allocation_create'),
]

models.py
from datetime import date
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q, Sum
from djmoney.models.fields import MoneyField


class Account(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    owned = models.BooleanField(default=True)

    @property
    def related_balances(self):
        return AccountBalance.objects.filter(account=self)

    @property
    def last_balance(self):
        return self.related_balances.latest()

    @property
    def balance_estimate(self):
        last = self.last_balance
        balance = last.balance

        for transaction in self.related_transactions.filter(date__gt=last.date):
            balance += transaction.net_amount(self)
        return balance

    @property
    def recent_transactions(self):
        return self.related_transactions.order_by("-date", "-pk")

    @property
    def related_transactions(self):
        return Transaction.objects.filter(Q(payee=self) | Q(payer=self))

    def transactions_between(self, date_start, date_end):
        """Transactions t: `date_bef` <= t.date < `date_end`"""
        return self.related_transactions.filter(date__range=(date_start, date_end))

    def categorise(self, date_start, date_end):
        categories = {}
        for t in self.transactions_between(date_start, date_end):
            categories.setdefault(t.category, 0)
            categories[t.category] += t.net_amount(self)
        return categories

    def balance_after(self, transaction):
        balance = AccountBalance.objects.filter(account=self, date__lt=transaction.date).order_by('-date').first()
        if not balance:
            return None

        value = balance.balance
        for t in self.related_transactions.filter(date__gt=balance.date, date__lte=transaction.date):
            if t.date < transaction.date or t.pk <= transaction.pk:
                value += t.net_amount(self)
        return value

    def find_discrepancies(self, date_start, date_end):
        balances = self.related_balances.filter(date__range=(date_start, date_end))
        return [(b,d) for (b, d) in ((b, b.difference) for b in balances) if d]

    def __str__(self):
        return self.name


class AccountBalance(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    balance = MoneyField(max_digits=16, decimal_places=2, default_currency="GBP")
    date = models.DateField()

    @property
    def last_transaction(self):
        return self.account.related_transactions.filter(date__lte=self.date).order_by('-date', '-pk').first()

    @property
    def previous_record(self):
        return AccountBalance.objects.filter(account=self.account, date__lt=self.date).order_by('-date').first()

    @property
    def difference(self):
        expected = None
        if self.last_transaction is not None:
            expected = self.account.balance_after(self.last_transaction)
        elif self.previous_record is not None:
            expected = self.previous_record.balance
        if expected is not None:
            return self.balance - expected
        return None

    def __str__(self):
        return str(self.balance)

    class Meta:
        get_latest_by = "date"
        verbose_name = "balance record"


class TransactionCategory(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def month_change(self):
        changes = {}
        for transaction in Transaction.objects.filter(category=self, date__gte=date.today().replace(day=1)):
            currency = transaction.amount.currency
            if currency not in changes:
                changes[currency] = 0
            changes[currency] += transaction.net_change
        return changes

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "category"
        verbose_name_plural = "categories"


class Transaction(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    payee = models.ForeignKey(Account, on_delete=models.CASCADE, related_name="payee", blank=True)
    payer = models.ForeignKey(Account, on_delete=models.CASCADE, related_name="payer",  blank=True)
    date = models.DateField()
    category = models.ForeignKey(TransactionCategory, on_delete=models.CASCADE)
    remark = models.CharField(max_length=50, blank=True)
    amount = MoneyField(max_digits=16, decimal_places=2, default_currency="GBP")

    @property
    def internal(self):
        return self.payee.owned and self.payer.owned

    @property
    def internal_change(self):
        # neg if paid someone else, pos oth: see category Internal
        return self.amount * (-1 if self.payer.owned and not self.payee.owned else 1)

    @property
    def net_change(self):
        # Paid someone else or vice-versa
        if self.payer.owned and not self.payee.owned:
            return -1 * self.amount
        elif not self.payer.owned and self.payee.owned:
            return self.amount
        else:
            return 0

    def net_amount(self, account):
        # Flows from an account
        return self.amount * (-1 if account == self.payer else 1)

    def __str__(self):
        return "%s (%s: %s)" % (self.amount, self.category, self.remark)

    class Meta:
        get_latest_by = ["date", "pk"]


class Budget(models.Model):
    EXPENDITURE = 0
    ALLOCATION = 1

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    accounts = models.ManyToManyField(Account)
    remark = models.TextField()
    date_start = models.DateField()
    date_end = models.DateField()
    categories = models.ManyToManyField(TransactionCategory, through="BudgetAllocation")

    def categorise(self):
        categories, totals = {}, {}
        # {Category: {Currency: {EXP: 3, ALLOC: 5}}

        for account in self.accounts.all():
            for c, s in account.categorise(self.date_start, self.date_end).items():
                currency = categories.setdefault(c, {}).setdefault(s.currency, {})
                currency.setdefault(Budget.EXPENDITURE, 0)
                currency[Budget.EXPENDITURE] += s
                currency = totals.setdefault(s.currency, {})
                currency.setdefault(Budget.EXPENDITURE, 0)
                currency[Budget.EXPENDITURE] += s

        for alloc in self.budgetallocation_set.all():
            currency = categories.setdefault(alloc.category, {}).setdefault(alloc.amount.currency, {})
            currency.setdefault(Budget.ALLOCATION, 0)
            currency[Budget.ALLOCATION] += alloc.amount
            currency = totals.setdefault(alloc.amount.currency, {})
            currency.setdefault(Budget.ALLOCATION, 0)
            currency[Budget.ALLOCATION] += alloc.amount
        return categories, totals

    def __str__(self):
        return self.name


class BudgetAllocation(models.Model):
    budget = models.ForeignKey(Budget,on_delete=models.CASCADE)
    category = models.ForeignKey(TransactionCategory, on_delete=models.CASCADE)
    amount = MoneyField(max_digits=16, decimal_places=2, default_currency="GBP")

    @property
    def owner(self):
        return self.budget.owner

    def __str__(self):
        return "%s (%s)" % (self.category, self.amount)

templates/balance/account_form.html
{% extends "balance/base.html" %}
{% load bootstrap4 %}

{% block content %}
<h1>New account</h1>

<form method="post" action="{% url 'balance:account_create' %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Create</button>
    {% endbuttons %}
</form>
{% endblock content %}

templates/balance/account_list.html
{% extends "balance/base.html" %}

{% block title %}: Accounts{% endblock %}

{% block content %}
<h1>Your accounts
    <small>
        <a class="btn btn-md btn-success" href="{% url 'balance:account_create' %}" role="button">Add</a>
    </small>
</h1>

{% include "balance/account_table.html" with account_list=owned_accounts %}

<h2>Other accounts</h2>
{% include "balance/account_table.html" with account_list=other_accounts %}

{% endblock content %}

templates/balance/accountbalance_form.html
{% extends "balance/base.html" %}
{% load bootstrap4 %}

{% block content %}
<h1>Update Balance</h1>

<form method="post" action="{% url 'balance:balance_update' %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Update</button>
    {% endbuttons %}
</form>
{% endblock content %}

templates/balance/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
{% load balance_extras %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Balance{% block title %}{% endblock %}</title>
    {% bootstrap_css %}

    <link href="{% static 'balance/style.css' %}" rel="stylesheet">

    {% block scripts %}{% endblock %}
</head>

<body>
<header>
    {% include 'balance/nav.html' %}
</header>
<div class="container-fluid">
    <div class="row">
        <nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
            <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                    <a class="nav-link {% nav_active request 'balance:account_list' %}" href="{% url 'balance:account_list' %}">Accounts Overview</a>
                </li>
            </ul>
            <hr>
            <ul class="nav nav-pills flex-column">
                {% for account in request.user.account_set.all %}
                {% if account.owned %}
                <li class="nav-item">
                    <a class="nav-link {% nav_active request 'balance:account_detail' account.pk %}" href="{% url 'balance:account_detail' account.pk %}">{{ account }}</a>
                </li>
                {% endif %}
                {% endfor %}
            </ul>
        </nav>

        <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
            {% block content %}
            {% endblock content %}
        </main>
    </div>
</div>
</body>
</html>

templates/balance/budget_form.html
{% extends "balance/base.html" %}
{% load bootstrap4 %}

{% block content %}
<h1>New budget</h1>

<form method="post" action="">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Create</button>
    {% endbuttons %}
</form>
{% endblock content %}

templates/balance/budget_list.html
{% extends "balance/base.html" %}

{% block title %}: Budgets{% endblock %}

{% block content %}
<h1>Your budgets
    <small>
        <a class="btn btn-md btn-success" href="{% url 'balance:budget_create' %}" role="button">Add</a>
    </small>
</h1>

<ul>
    {% for object in object_list %}
    <li><a href="{% url 'balance:budget_detail' object.pk %}">{{ object }}</a></li>
    {% endfor %}
</ul>

{% endblock content %}

templates/balance/category_archive_month.html
{% extends "balance/base.html" %}

{% block title %}: {{ category }}{% endblock %}

{% block content %}
<h1>{{ category }}</h1>

{% include "balance/transaction_archive.html" with transaction_list=object_list url_name='balance:category_month' object_key=category.pk %}

{% endblock %}

templates/balance/nav.html
{% load balance_extras %}

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{% url 'balance:account_list' %}">Balance</a>

    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link {% nav_active request 'balance:category_list' %}" href="{% url 'balance:category_list' %}">Categories</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% nav_active request 'balance:budget_list' %}" href="{% url 'balance:budget_list' %}">Budgets</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% nav_active request 'balance:transaction_create' %}" href="{% url 'balance:transaction_create' %}">New Transaction</a>
            </li>
        </ul>
    </div>
</nav>

templates/balance/transaction_archive.html
<h2>Transactions</h2>

<nav>
  <ul class="pagination">
    <li class="page-item">
      <a class="page-link" href="{% url url_name object_key previous_month.year previous_month.month %}" tabindex="-1">
        {{ previous_month|date:"N" }}</a>
    </li>
    <li class="page-item active">
      <span class="page-link">
        {{ month|date:"N Y" }}
      </span>
    </li>
    <li class="page-item">
      <a class="page-link" href="{% url url_name object_key next_month.year next_month.month %}">
        {{ next_month|date:"N" }}</a>
    </li>
  </ul>
</nav>

{% include "balance/transaction_table.html" %}

templates/balance/transaction_archive_month.html
{% extends "balance/base.html" %}

{% block content %}
<h1>{{ category }}</h1>

<h2>Transactions <small>{{ month|date:"N Y" }}</small></h2>
<p><a href="{% url 'balance:category_month' category.pk previous_month.year previous_month.month %}">Previous</a>
    <a href="{% url 'balance:category_month' category.pk next_month.year next_month.month %}">Next</a></p>
{% include "balance/transaction_table.html" with transaction_list=object_list %}

{% endblock %}

templates/balance/transaction_detail.html
{% extends "balance/base.html" %}
{% load bootstrap4 %}

{% block content %}
<h1>Transaction
    <small>
        <a class="btn btn-md btn-success" href="{% url 'balance:transaction_update' transaction.pk %}" role="button">Update</a>
        <a class="btn btn-md btn-danger" href="{% url 'balance:transaction_delete' transaction.pk %}" role="button">Delete</a>
    </small>
</h1>

<h2>{{ transaction.date }}</h2>

<ul>
    <li>From: <a href="{% url 'balance:account_month' transaction.payer.pk transaction.date.year transaction.date.month %}">{{ transaction.payer }}</a></li>
    <li>To: <a href="{% url 'balance:account_detail' transaction.payee.pk %}">{{ transaction.payee }}</a></li>
    <li>Category: <a href="{% url 'balance:category_month' transaction.category.pk transaction.date.year transaction.date.month %}">{{ transaction.category }}</a></li>
    <li>Amount: {{ transaction.amount }}</li>
    <li>Remark: {{ transaction.remark|default:"-" }}</li>
</ul>

{% endblock %}

templates/balance/transaction_form.html
{% extends "balance/base.html" %}
{% load bootstrap4 %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.9/select2-bootstrap.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>

<script type="text/javascript">
$(document).ready(function() {
  $.fn.select2.defaults.set( "theme", "bootstrap" );
  $("select").select2().on("select2:close", function (evt) {
    setTimeout(function() {
      $('.select2-container-active').removeClass('select2-container-active');
      $(':focus').blur();
      evt.target.focus();
    }, 1);
  });
});
</script>
{% endblock scripts %}

{% block content %}
{% if form.instance.pk %}
<h1>Update Transaction</h1>
{% else %}
<h1>New Transaction</h1>
{% endif %}

<form method="post" action="">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Save</button>
    {% endbuttons %}
</form>
{% endblock content %}

templates/balance/transaction_table.html
{% load balance_extras %}

{% if transaction_list %}
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Date</th>
            <th>Category</th>
            <th>From</th>
            <th>To</th>
            <th>Amount</th>
            {% if account %}<th>Balance</th>{% endif %}
            <th>Remark</th>
        </tr>
        </thead>

        <tbody>
        <tr class="table-primary">
            <td colspan="4"><strong>Total</strong></td>
            <td><strong>{% for sum in total.values %}{{ sum }} {% empty %}-{% endfor %}</strong></td>
            <td colspan="3"></td>
        </tr>
        {% for transaction in transaction_list %}
        {% if transaction.internal and not account %}<tr class="text-muted">{% else %}<tr>{% endif %}
            <td><a href="{% url 'balance:transaction_detail' transaction.pk %}">{{ transaction.date }}</a></td>
            <td><a href="{% url 'balance:category_detail' transaction.category.pk %}">{{ transaction.category }}</a></td>
            <td><a href="{% url 'balance:account_detail' transaction.payer.pk %}">{{ transaction.payer }}</a></td>
            <td><a href="{% url 'balance:account_detail' transaction.payee.pk %}">{{ transaction.payee }}</a></td>
            {% if account %}
            <td>{{ transaction|net_amount:account }}</td>
            <td>{{ transaction.balance_after|default:"-" }}</td>
            {% else %}
            <td>{{ transaction.internal_change }}</td>
            {% endif %}
            <td>{{ transaction.remark }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<p>No transactions</p>
{% endif %}

templates/balance/transactioncategory_form.html
{% extends "balance/base.html" %}
{% load bootstrap4 %}

{% block content %}
<h1>New Category</h1>

<form method="post" action="{% url 'balance:category_create' %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Create</button>
    {% endbuttons %}
</form>
{% endblock content %}